name: 2018
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  CARGO_TERM_COLOR: always
  RUSTC_BOOTSTRAP: 1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deps
        run: sudo apt install lcov libxcb-shape0-dev libxcb-xfixes0-dev
      - name: fmt
        run: make fmt
        working-directory: 2018
      - name: clippy
        run: make clippy
        working-directory: 2018
      - name: test
        run: make test
        working-directory: 2018
      - name: more deps
        run: cargo install grcov
      - name: coverage
        run: make coverage-ci
        working-directory: 2018
      - name: list
        run: ls -lhart target/debug
        working-directory: 2018
      - name: codecov
        run: bash <(curl -s https://codecov.io/bash) -f target/debug/lcov.info
        working-directory: 2018
